import { Agent, Project, MemoryEntry, Handoff, McpConnector, Task, Message } from '../types';

export const mockAgents: Agent[] = [
  {
    id: 'agent-codex',
    name: 'Codex Dev',
    provider: 'openai',
    model: 'gpt-4o',
    role: 'Full-stack Developer',
    strengths: ['coding', 'debugging'],
    weaknesses: ['creative writing'],
    status: 'idle',
    maxContextTokens: 128000,
    currentContextUsed: 15000,
    supportsTools: true,
    supportsVision: true,
    supportsAudio: true,
    supportsArtifacts: true,
    supportsCodeExecution: true,
    costInputPerMillion: 5.00,
    costOutputPerMillion: 15.00,
    fallbackPriority: 2,
    availableTools: ['file_writer', 'mcp_github'],
    permissions: ['fs_write', 'fs_read'],
    enabled: true,
  },
  {
    id: 'agent-claude',
    name: 'Claude Architect',
    provider: 'anthropic',
    model: 'claude-3-5-sonnet',
    role: 'System Architect',
    strengths: ['design', 'planning'],
    weaknesses: ['exact syntax'],
    status: 'working',
    maxContextTokens: 200000,
    currentContextUsed: 45000,
    supportsTools: true,
    supportsVision: true,
    supportsAudio: false,
    supportsArtifacts: true,
    supportsCodeExecution: false,
    costInputPerMillion: 3.00,
    costOutputPerMillion: 15.00,
    fallbackPriority: 1,
    availableTools: ['mcp_filesystem', 'browser', 'mcp_github'],
    permissions: ['fs_read'],
    enabled: true,
  },
  {
    id: 'agent-gemini',
    name: 'Gemini Vision',
    provider: 'gemini',
    model: 'gemini-1.5-pro',
    role: 'Multimodal Analyst',
    strengths: ['vision', 'large context'],
    weaknesses: ['fast response'],
    status: 'idle',
    maxContextTokens: 2000000,
    currentContextUsed: 500,
    supportsTools: true,
    supportsVision: true,
    supportsAudio: true,
    supportsArtifacts: false,
    supportsCodeExecution: true,
    costInputPerMillion: 3.50,
    costOutputPerMillion: 10.50,
    fallbackPriority: 3,
    availableTools: ['image_gen', 'search', 'mcp_filesystem'],
    permissions: ['web_search'],
    enabled: true,
  },
];

export const mockProjects: Project[] = [
  {
    id: 'proj-1',
    name: 'AURA Command Center (Self)',
    localPath: '/User/dev/aura-command-center',
    githubRepo: 'owner/aura-command-center',
    activeAgentId: 'agent-claude',
    memoryFolder: '/User/dev/aura-command-center/.memory',
    summary: 'A desktop application bridging multiple LLM agents together via a unified local memory loop.',
    environmentNotes: 'Node 20 / Tauri / React',
  },
  {
    id: 'proj-2',
    name: 'E-commerce API',
    localPath: '/User/dev/ecommerce-backend',
    activeAgentId: 'agent-codex',
    memoryFolder: '/User/dev/ecommerce-backend/.agent-logs',
    summary: 'Rust Actix-web backend for a shoe store.',
    environmentNotes: 'Rust 1.78, PostgreSQL',
  },
];

export const mockConnectors: McpConnector[] = [
  {
    id: 'mcp-github',
    name: 'GitHub MCP',
    type: 'mcp',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-github'],
    env: {
      GITHUB_TOKEN: '********',
    },
    enabled: true,
    allowedAgents: ['agent-claude', 'agent-codex'],
    status: 'connected',
  },
  {
    id: 'mcp-fs',
    name: 'Local Filesystem MCP',
    type: 'mcp',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-filesystem', '/User/dev'],
    env: {},
    enabled: true,
    allowedAgents: ['agent-claude', 'agent-codex', 'agent-gemini'],
    status: 'connected',
  },
];

export const mockMemory: MemoryEntry[] = [
  {
    id: 'mem-1',
    timestamp: new Date().toISOString(),
    projectId: 'proj-1',
    agentName: 'Claude Architect',
    category: 'decision',
    title: 'Architecture Chosen',
    summary: 'Decided to use React + Vite + Tauri for the frontend.',
    details: 'Because Tauri uses the native webview, it provides a smaller binary size than Electron while allowing us to use familiar web technologies.',
    relatedFiles: ['package.json', 'src-tauri/tauri.conf.json'],
    tags: ['architecture', 'frontend'],
    status: 'resolved',
  },
  {
    id: 'mem-2',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    projectId: 'proj-1',
    agentName: 'Codex Dev',
    category: 'error',
    title: 'SQLite Native Build Failed',
    summary: 'Failed to build better-sqlite3 native bindings in CI.',
    details: 'The CI runner is missing python3 and build-essential.',
    relatedFiles: ['.github/workflows/build.yml'],
    tags: ['ci', 'sqlite'],
    status: 'active',
  },
];

export const mockHandoffs: Handoff[] = [
  {
    id: 'ho-1',
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    projectId: 'proj-1',
    fromAgentId: 'agent-claude',
    toAgentId: 'agent-codex',
    goal: 'Implement the database schema discussed in the architecture spec.',
    completedTasks: ['Defined SQLite schema', 'Created migration script'],
    failedTasks: ['Implementing the actual Rust Tauri command to initialize DB'],
    filesChanged: ['src/db/schema.sql', 'src/db/migrations/001.sql'],
    filesToReview: ['src-tauri/src/main.rs'],
    nextRecommendedAction: 'Please write the Rust boilerplate for executing src/db/schema.sql on Tauri app startup.',
    warnings: ['Make sure to use the tauri-plugin-sql or rusqlite safely.'],
  },
];

export const mockTasks: Task[] = [
  {
    id: 'task-1',
    projectId: 'proj-1',
    title: 'Build Desktop Shell Layout',
    status: 'completed',
    assignedAgentId: 'agent-claude',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 43200000).toISOString(),
  },
  {
    id: 'task-2',
    projectId: 'proj-1',
    title: 'Scaffold Mock Data Layer',
    status: 'completed',
    assignedAgentId: 'agent-codex',
    createdAt: new Date(Date.now() - 43200000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task-3',
    projectId: 'proj-1',
    title: 'Implement Local System Terminal Connector',
    status: 'in_progress',
    assignedAgentId: 'agent-claude',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockMessages: Message[] = [
  {
    id: 'msg-1',
    role: 'user',
    content: 'Can you sketch out the main layout?',
    timestamp: new Date(Date.now() - 600000).toISOString(),
  },
  {
    id: 'msg-2',
    role: 'system',
    agentId: 'AURA Config',
    content: 'AURA created a workspace plan. Selected target: /User/dev/agent-command-center. Branch: aura-agent-worktree-1',
    timestamp: new Date(Date.now() - 590000).toISOString(),
  },
  {
    id: 'msg-3',
    role: 'assistant',
    agentId: 'agent-claude',
    content: 'Claude generated a UI plan. The application will use a split-pane layout with a central command console and a right sidebar for runtime artifacts.',
    timestamp: new Date(Date.now() - 580000).toISOString(),
  },
  {
    id: 'msg-4',
    role: 'assistant',
    agentId: 'agent-codex',
    content: 'Codex is requesting permission to run npm install to add lucide-react.',
    timestamp: new Date(Date.now() - 200000).toISOString(),
    toolCalls: [
      {
        name: 'npm.install',
        args: '["lucide-react"]',
        status: 'pending'
      }
    ]
  },
  {
    id: 'msg-5',
    role: 'system',
    agentId: 'Workspace Runner',
    content: 'Dev server mock started at http://localhost:5173. Preview artifact created.',
    timestamp: new Date(Date.now() - 150000).toISOString(),
  },
  {
    id: 'msg-6',
    role: 'system',
    agentId: 'Browser Agent',
    content: 'Browser console warning detected: Invalid DOM property `class`. Corrected in next patch.',
    timestamp: new Date(Date.now() - 100000).toISOString(),
  },
  {
    id: 'msg-7',
    role: 'system',
    agentId: 'AURA Router',
    content: 'Handoff prepared for another agent. Claude has completed the architecture plan, passing context to Codex for implementation.',
    timestamp: new Date(Date.now() - 50000).toISOString(),
  }
];
